# Generated by Django 4.1.5 on 2023-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kycinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycinfo',
            old_name='author',
            new_name='autheur',
        ),
        migrations.RenameField(
            model_name='kycinfo',
            old_name='dateofbirth',
            new_name='dateExpiration',
        ),
        migrations.RenameField(
            model_name='kycinfo',
            old_name='expirationdate',
            new_name='dateNaissance',
        ),
        migrations.RenameField(
            model_name='kycinfo',
            old_name='name',
            new_name='lieuNaissance',
        ),
        migrations.RenameField(
            model_name='kycinfo',
            old_name='placeofbirth',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='kycinfo',
            old_name='surname',
            new_name='nomFamille',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='titre',
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='sex',
            field=models.CharField(max_length=1),
        ),
    ]
